app:
  datasource:
  main:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always

